### ISSUE TITLE
General Design Question

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#29]
Should we be having me send you JSON objects that you parse with inputs instead of lots of get data in URLs? Seems like better practice. Seems easy enough on the PHP side, definitely easy on the JS side to send.

http://stackoverflow.com/questions/9597052/how-to-retrieve-request-payload

**Comment by joelmeister** [comment]
Doesn't matter to me, its literally just adding json_decode() to the top of
the controllers

**Comment by c-topherl** [comment]
Let's do that then-feels less hacky that way to me.
