### ISSUE TITLE
fix get_delivery_options

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#31]
Current response:

{
    "status":"success",
    "message":"This feature is not implemented, but always will return \"pickup\" for now",
    "response":{
        "delivery_dates":"20160330",
        "delivery_methods":["pickup"],
        "warehouses":["warehouses not supported"]}
}

What it should be... I noted in a doc somewhere that I need titles/values for everything (human readable description/codes our program(s) can make sense of). Further, we should have arrays of objects, not arrays of strings since each entry has multiple attributes.

{
    "status":"success",
    "message":"This feature is not implemented, but always will return \"pickup\" for now",
    "response":{
        "delivery_dates": [
            {"title":"03/30/2016", "value":"20160330"}
            {"title":"03/31/2016","value":"20160331"}
        ],
        "delivery_methods": [
            {"title":"pickup", "value": 0}
        ],
        "warehouses": [
            {"title":"Warehouse A","value": 0}
        ]
    }
}

**Comment by joelmeister** [comment]
Can you not parse the data on the JS side

**Comment by joelmeister** [comment]
ok updated  For delivery dates, I return the next 7 days starting with tomorrow.  I created a delivery_methods table, so for now those are all being selected.  Warehouses returns a value and description (value/title as the response for consistency), but not much else ATM.

1)  How many days out should this go by default?  We will set up a way to control that by the customer, but I think that other things have higher priority for right now
2)  No restrictions yet, check out [issue 34](https://github.com/c-topherl/brewCom/issues/34)
3)  Should warehouses be returning any other address information?  We have all of that info on there.
