### ISSUE TITLE
Question: Customer table

### ISSUE THREAD

**Issue by joelmeister** [c-topherl/brewCom#35]
Since we have decided to make the orders and whatnot per user rather than per customer, most of the add order/cart functions will not need to accept "customer code".  

I was planning on adding "customer id" to the users table and only allow each user to belong to one customer so we could just join the customers table whenever we need customer information.  Then I will add "customer_id" as an option for the get_\* operations.  

This is all my current plan anyways.  Thoughts/issues?

**Comment by c-topherl** [comment]
Works for me.
