### ISSUE TITLE
Question: update cart

### ISSUE THREAD

**Issue by joelmeister** [c-topherl/brewCom#36]
What exactly will the response be?  Will it 1) have all of the lines for the cart so I can delete everything and just re-add or 2) could you append a "command" (add/delete/update) to each line?  

Or 3) do you just want me to make it "smart" so that:
0 quantity deletes matching product/unit (or does nothing if the line doesnt exist)
greater than 0 quantity, existing product/unit updates
greater than 0 quantity, no existing product/unit adds

1) would probably be easiest since I could just delete all cart_detail records with matching user_id and call the add_cart_detail function again
2) would also be really easy, and probably the best/most explicit.  plus the "last_updated" column on the cart_detail line would actually be accurate. 
3) has certain limitations i.e. no 0 quantity lines, only one line for each product/unit pair.

Thoughts?

**Comment by joelmeister** [comment]
Thinking something along the lines of

```
{
    details : [
        {
            command : ('add'/'update'/'delete'),
            product_id : id,
            unit_id: id,
            price: price,
            quantity:quantity
        }   
    ]  
}
```

**Comment by c-topherl** [comment]
I think option 1 is feasible/reasonable. No matter how you get to the cart page, it calls the same logic from there right now, so everything will be recalculated. Pretty sure that's how it works as-is for the front end (send everything again).

**Comment by c-topherl** [comment]
Honestly what the logic probably should be, is in add_cart_detail request, check if the cart already has lines-if so, overwrite them. Otherwise, just add them. As it stands right now, I'm not telling you anything different between updating and creating, and I think modifying it to be able to tell you the difference would be a hassle.
