### ISSUE TITLE
Add data to get_order_details

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#39]
Can we add some order header information to the order_detail response? Specifically...

-Order number
-Delivery method
-Delivery date
-Order total $$$

It would be at the same level as the order_details array, like so:

responseData: {
          id: 13,
          order_total: $55,
          delivery_method: blah,
          delivery_type: blah,
         order_details: [
                  .
                  .
                  . 
         ]
}

**Comment by joelmeister** [comment]
do you think it would make sense to just add "details" to the main get_orders function specified by a flag?

like
function=get_orders&order_id=(id)&(other options....)&details

The flag would be in case you don't want to the details coming back.

I'm just thinking I don't want too much duplicate code.  I would keep the get_order_details function in case you ever really do just want the details.  Just a thought, wouldn't be a big deal either way.  what do you think?

**Comment by c-topherl** [comment]
My concern is we're probably going to end up needing wayyyy more header information for the detail request eventually (for the dashboard) while the get_orders request will always be to show a summary of orders in a table that you can drill into if you'd like, so I don't see any data being added there.

But, if we do add data, I suppose it wouldn't hurt to just have too much data coming back?

I think the best way to avoid duplicate code would be for you to just set a flag based on what function is passed in and then:

`if(flag)
        $response_object = add_order_detail($response_object, $order_id);`

**Comment by c-topherl** [comment]
Scratch my initial notes, just look at the API doc-I added a lot more data (for dashboard) than those 4 things.

https://docs.google.com/document/d/1I-c6GTfSP8AxRKGj51cr06IzN5tdu_RUg2w_aj1sdxk/edit

**Comment by c-topherl** [comment]
And based on this, I think the requests are really morphing into:

get_orders - get a list of the orders the fit the criteria and basic identifying criteria (id, delivery date, total)

get_order_details - not literally "get lines of order", but rather "get more intricate details about the order to be displayed", which just happen to include the order lines.

**Comment by joelmeister** [comment]
works for me I'll get going on this stuff

**Comment by joelmeister** [comment]
Ok this is done, but don't have any addresses yet so those are returning null, so I will need to create an add address function.

right now i have added addresses, user_addresses table, customer_addresses tables and then address_id to orders and cart_headers tables.

**Comment by c-topherl** [comment]
If this is done why did you assign to me? Can we close?

**Comment by joelmeister** [comment]
good question.  i think so you can start working on the front end for address stuff for this and letting me know if there are any issues. and so you can double check you have all the information you need
