### ISSUE TITLE
Fix verify_user (cart) response

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#40]
Issues I see with the response in the case that a cart is found:

-Your response attribute is a cart object... within a cart object. Get rid of one of the layers.

-Your detail array is called details, mine is lines. I don't care what we call it but it has to match. Make sure each line has these attributes: product_code, product_description, unit_description, price, quantity.

-As it stands, this cart for the test customer doesn't have any lines. This will lead to an empty table. What should we do in that case? Direct to the order page instead?

**Comment by joelmeister** [comment]
1) fixed
2) i changed mine to 'lines'.  makes more sense since we are now using 'details' as detailed header and line information
3) i think that would make the most sense
