### ISSUE TITLE
displayTable not working

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#44]

**Comment by c-topherl** [comment]
I think this is working... passing to Joel for testing.

**Comment by joelmeister** [comment]
When I hit "Checkout" and then "Back" I lose all of the lines from the cart with the message "No data available in table".  

Also, when we hit "Back" from the shopping cart page, would it be hard to automatically fill back in the data on the order page?

**Comment by joelmeister** [comment]
Nevermind, just read the other bug.
