### ISSUE TITLE
Write getCart() 

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#45]

**Comment by c-topherl** [comment]
I wrote a getCart function and modified the back button on the checkout page to call it in order to reload the cart page. It's currently broken because of the response format. It's currently giving me:

{
response: {
cart: {
//data
}
}

I need the cart object gone, and just move the data up one level into the response object.

**Comment by joelmeister** [comment]
You use the "cart" object on the verifyLogin, so one of those two needs to change.

**Comment by c-topherl** [comment]
True. That function is hardcoded though, so final answer is going to be get rid of the cart object. That one line in template_controller.js will have to change.

data = responseObj.response.cart;

becomes:

data = responseObj.response;

We can change the delivery options version to not have the delivery options object in there too for "best practice" if you want-I don't really care.

**Comment by joelmeister** [comment]
"Best practice", you told me awhile back that best practice was to send back a container for what was in the response i.e. have all of the cart info contained in responseObj.response.cart, all of the products in responseObj.response.products, etc.  If we are saying this is the new best practice, then all of the "get" functions should change so the responseObj.response directly contains the data you want.

**Comment by c-topherl** [comment]
True, but the problem now is that I'm grabbing the response data arbitrarily in the HTTP request method.

``` javascript
if (response.status === "success")
    loadTemplate(response.data);
```

It doesn't really make sense to have to know what the inner object is called for each different request. So... I take it back.

**Comment by c-topherl** [comment]
I pushed changes to not expect cart or delivery options objects anymore.

**Comment by joelmeister** [comment]
word back end is updated as well

**Comment by c-topherl** [comment]
Haven't been able to test cuz I'm on my work laptop but I'm gonna close this.
