### ISSUE TITLE
get_orders request

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#59]
You're sending back "delivery method: <delivery_code>". Can we get a human readable description instead so the user doesn't see a number in the table cell? You can either simply translate the code to the description and send that instead, or switch to sending two values like below... doesn't matter to me.

delivery_method_code: 0,
delivery_method: Pickup

**Comment by joelmeister** [comment]
delivery_method_id => this is the integer id
delivery_method => this is a human readable version
