### ISSUE TITLE
Flow of site discussion

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#63]
The get delivery options request should probably detect if a user already has a cart and, if they do, direct them to the cart page instead.

Otherwise, right now, if they log in and have a cart and then click anything in the menu, their order gets lost with no way to continue it-trying to start a new order results in the delivery page, and then an error creating the cart header because one already exists. I guess another option would be to overwrite the existing cart (or prompt the user to do so?).

What do you think?

**Comment by joelmeister** [comment]
I think that is a good idea.  If they hit "place order" but already have a cart, then populate that page instead.

**Comment by joelmeister** [comment]
Assigned back to you to play around with storing that on the front end.  Pass back to me if I need to change anything
