### ISSUE TITLE
Refreshing page takes you back to log in page

### ISSUE THREAD

**Issue by joelmeister** [c-topherl/brewCom#65]
How do most sites handle this?  Store a session variable on the client and then verify the integrity of that on the server?

**Comment by c-topherl** [comment]
It's because we're dynamically replacing the content of a div when you click through pages, not reloading entire pages. I'll look into this when I get a chance:

https://css-tricks.com/dynamic-page-replacing-content/

**Comment by c-topherl** [comment]
This is going to force me to completely refactor how pages are loaded. Is it worth all the effort, or should we just say they have to use the back buttons I've built into the site?

**Comment by joelmeister** [comment]
For now I think we can just leave it like this.  Once we get the user login in session stored, then it will at least take them to the cart or order page rather than the log in page, which would mostly get rid of the annoyance.  Could we have an alert when you hit refresh that says something like "Are you sure?  Navigating from the page may cause you to lose form data"?  I think that would help people unexpectedly refreshing or help them know what's going on rather than just losing their page.

**Comment by c-topherl** [comment]
Based on this link, I don't know if it's possible:

http://stackoverflow.com/questions/8078650/can-we-disable-browsers-buttonsback-forward-refresh-by-javascript

**Comment by c-topherl** [comment]
This will be mostly solved with tokens so I'm closing this.
