### ISSUE TITLE
Implement update customer info

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#68]
Assigned to you so you can give me a sample request that works so I know what to send. Then you can give it back to me.

**Comment by joelmeister** [comment]
Right now customers table only has code and name, and then there is a customer_addresses table.  Those functions will be take the regular address info and then the customer id (or code).  I will write a sample request once those get built out.

**Comment by joelmeister** [comment]
Here is the sample requests.  All requests go to customer_controller.php

**Add**

```
{   function:add_customer,
    code:<custCode>,
    name:<name>,
    active:<0/1>}
```

active is optional.  returns all customer info. Sample response:
`"response":{
    "function":"add_customer",
    "code":"test4",
    "name":"Test customer 4",
    "active":1,
    "id":"8"}`

**Update**

```
{   function:update_customer,
    id:<custId>,
    code:<custCode>,
    name:<name>,
    active:<0/1>}
```

id and at least one other required.  returns id,code,name,active. Sample response:
`"response":{
    "function":"update_customer",
    "id":"5",
    "code":"test",
    "name":"test customer",
    "active":"1"}`

**Get**

```
{   function:get_customers,
    id:<custId>,
    code:<custCode>,
    active:<0/1>}
```

only function required.  Samples response:
`"response":[
    {"id":"5",
    "code":"test",
    "name":"test customer",
    "active":"1",
    "last_updated":"2016-04-17 23:23:29"}]`

Will create address functions and post details.

**Comment by joelmeister** [comment]
**Add address**

```
{   function:add_address,
    customer_id:<custId>,
    name:<custName>,
    address1:<add1>,
    address2:<add2>,
    city:<city>,
    state:<2digitStateCode>,
    zipcode:<zipCode>,
    type:<0/1>}
```

everything but address2 required.  Didn't actually update state column to only allow 2 digit code, but I will, please just send it that way for now and I will update the code when I get a minute.  returns address_id.  "type" is 0 = shipping , 1 = billing
`"response":{"address_id":"8"}`

**Get addresses**

```
{   function:get_addresses,
    customer_id:<custId>,
    user_id:<userId>}
```

customer_id OR user_id required.  you may pass both.  returns array of addresses for the user/customer
`"response":[{"address_id":"1","last_updated":"2016-04-17 23:39:49","name":"joel1","address1":"11010 Domain Drive","address2":"Apt 11308","city":"Austin","state":"Texas","zipcode":"78750","type":"0"},{"address_id":"4","last_updated":"2016-04-17 23:29:18","name":"test customer","address1":"208 N Harris St","address2":"","city":"Bourbon","state":"IN","zipcode":"46504","type":"1"}]`

**Comment by joelmeister** [comment]
**Update address**

```
{   function:update_address,
    customer_id:<custId>,
    user_id:<userId>,
    name:<custName>,
    address1:<add1>,
    address2:<add2>,
    city:<city>,
    state:<2digitStateCode>,
    zipcode:<zipCode>,
    type:<0/1>}
    }
```

address_id and (customer_id OR user_id) required to update.  all others are optional
`"response":{"address_id":"4","last_updated":"2016-04-17 23:29:18","name":"Test Customer","address1":"208 N Harris St","address2":"","city":"Bourbon","state":"IN","zipcode":"46504","type":"1","function":"update_address","customer_id":"5"`

**Comment by joelmeister** [comment]
Let me know if any of these requests aren't working right for you.  We can add stuff to the customer table, just wanted to get the bare minimum going for now.

**Comment by c-topherl** [comment]
Will definitely need these functions for the dashboard side, but I figured for MVP on the customer side, updating should just be simple account info for now. What do you think? I don't see any of these fields mentioned above:

![image](https://cloud.githubusercontent.com/assets/10346101/15169849/a2936e22-16f4-11e6-9320-8b5bde39ea2a.png)

**Comment by joelmeister** [comment]
"Customer" or "user"?  There's already been an "update_user" request that you just need to post to the customer_controller.  It requires "id" and accepts all of those fields optionally.

**Comment by joelmeister** [comment]
`
{   function:update_user,
    user_id:<userId>,
    email:<newEmail>,
    password:<password>,
    username:<newUsername>
    }
`

response:
`
{"response":{"id":"1","email":"joelmeister1209@gmail.com","username":"joelmeister1209","token":"739100267a35720dbaab14c8ce4bcfaf"},"message":"User updated.","status":"success"}`

**Comment by c-topherl** [comment]
Ya, this is what I was looking for. We'd need to make sure all the fields are optional, though, if you didn't already.

**Comment by c-topherl** [comment]
When you say "accepts all those fields optionally", do you mean it checks if the field is in the request, and if it is, use it? Or that it checks if the value being sent for the field is blank, and only uses it if something is filled in?

What _should_ it be?

**Comment by joelmeister** [comment]
If it is there, it will use it.  There's probably scenarios you would want to blank it out

**Comment by c-topherl** [comment]
Sending user_id = 4, getting "user id '' does not exist!" failure message.

![image](https://cloud.githubusercontent.com/assets/10346101/15347501/2094b5ba-1c77-11e6-90d3-3b76fca0ee37.png)

![image](https://cloud.githubusercontent.com/assets/10346101/15347515/3727b8cc-1c77-11e6-83d5-593876efa914.png)

![image](https://cloud.githubusercontent.com/assets/10346101/15347534/41e84d08-1c77-11e6-80ff-8ee1353f7536.png)

**Comment by c-topherl** [comment]
I checked in my code updates for this, you should be able to check out and test when you're ready.

**Comment by joelmeister** [comment]
I'll check it out

**Comment by joelmeister** [comment]
Fixed.  I was taking "id" rather than "user_id".  Tested out a few different combos and things are looking bueno.

The email validation apparently doesn't like my company's domain )v: probably need to just make a quick change to that regex to allow numbers in the domain.

![image](https://cloud.githubusercontent.com/assets/5879383/15450483/29fdcc3e-1f62-11e6-8dfe-4bc1a83b073a.png)

![image](https://cloud.githubusercontent.com/assets/5879383/15450517/e516595a-1f62-11e6-8265-b6a28218c134.png)

**Comment by c-topherl** [comment]
Fixed.
