### ISSUE TITLE
Submit Order Request

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#70]
Getting a "column user_id cannot be null" when trying to call submit_order, but I'm definitely passing user_id. 

Here's the data I'm sending, viewed in Chrome debugger:

![image](https://cloud.githubusercontent.com/assets/10346101/14937808/949d7e50-0ec7-11e6-869d-c8e66b8f685e.png)

**Comment by c-topherl** [comment]
Turns out I wasn't sending any data with submit_order call before. Checking in changes to actually pass data now so you'll have to grab the latest JS.

**Comment by joelmeister** [comment]
Fixed, I didn't remove the "cart" index from the get_cart in the submit_order function.  

Now once an order is submitted, the message "Your order has been placed successfully!" won't go away until the page is refreshed.
