### ISSUE TITLE
Create user token

### ISSUE THREAD

**Issue by joelmeister** [c-topherl/brewCom#73]
On successful log in, store a user token which is a hash of the username, password, and current timestamp and return that with the log in response.  This token will be used to verify a user to bypass the log in and to submit orders.  Potentially this could be added to other requests as well.  Any request that requires a token will need the user_id or username to look up the token in the database.

For now, the token will "expire" if the "last login" is > 1 day old.  In the future this may turn in to a control setting.

**Comment by joelmeister** [comment]
{ "message" : "User verified",
  "response" : { "delivery_dates" : [ { "title" : "05/08/2016",
            "value" : "2016-05-08"
          }
        ],
      "delivery_methods" : [ { "code" : "pu",
            "title" : "Pick-up",
            "value" : "1"
          }
        ],
      "token" : "9e87877db3e15ca9b614bdf4136f0eb4",
      "user_id" : "1",
      "warehouses" : [ { "title" : "test warehouse",
            "value" : "1"
          } ]
    },
  "status" : "success"
}

**Comment by joelmeister** [comment]
On login, you can pass in the 'token' rather than the password.  Username or user_id is still required.  On successful login, the token and user_id are returned as part of the response, so you can store those in the browser.  As of right now, only the submit_order requires the user_id and token.  If you want to add them to other requests go ahead and do that and let me know and I can update those and test out.  It shouldn't break anything by passing an extra value to functions that don't support it yet.

**Comment by c-topherl** [comment]
Something that may need to be figured out down the line is how you're going to signal me if the token is expired.

However, there's a way for me to set expiration dates on cookies on the front end, so for now I'm just doing 1 day. So currently, without a setting, my cookie will just expire when your token expires.

**Comment by joelmeister** [comment]
I return a failure if the cookie expires just like if you enter the wrong
password

**Comment by c-topherl** [comment]
What are we returning as a failure message in that case? As the code stands right now, that error message will be presented to the user. If it's something like "expired token", that's probably bad. We could either...

1) Change the message to "Your session has expired. Please log in again."
2) Have me catch that case in my code and not display an error message, just have them log in as normal.

What do you think?

**Comment by joelmeister** [comment]
1)

**Comment by c-topherl** [comment]
Ok that's on you then. Other than that quick change, this is done and checked in.
