### ISSUE TITLE
Submit Order-respond with order data

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#74]
Can we modify the submit order request to return all the order data? It will be used to populate the new order confirmation page I checked in/implemented. To see the data/format I'm expecting, look at the requestData object in the submitOrder() function in template_controller.js.

**Comment by c-topherl** [comment]
Note-the same JSON data will then be used to populate the confirmation email.

**Comment by joelmeister** [comment]
delivery_date and addresses not filled out yet, but are returned in response, so all values are present.  Will connect those soon.

**Comment by c-topherl** [comment]
This response is super fucked up now. It's like you're doing echo "Array()" instead of echo Array(). Getting:

"Array(".... with a big long string of array values.

![image](https://cloud.githubusercontent.com/assets/10346101/15103198/6053b12c-155d-11e6-9c20-d6bdde219cc1.png)

**Comment by joelmeister** [comment]
Yea I was testing it out so hold off for a minuto

**Comment by joelmeister** [comment]
Ok this should all be good passing to you to verify.

**Comment by c-topherl** [comment]
Looks good.
