### ISSUE TITLE
Get order detail request

### ISSUE THREAD

**Issue by c-topherl** [c-topherl/brewCom#87]
Modify response to be the exact same as the response from submit order, please. 

I noticed the order confirmation page and the order detail page were almost the same thing so I removed confirmation.html and submitting an order now just directs to the orderdetail page. The confirmation page had more data in it-I copied all that over to order_detail.html.

**Comment by joelmeister** [comment]
submit_order actually calls get_order_detail at the end, so they are already the exact same.

**Comment by joelmeister** [comment]
Didn't mean to reopen
